import express from "express";
import { register, login } from "../controllers/authController.js";
import { upload } from "../utils/upload.js";
import { me } from "../controllers/meController.js";
import { protect } from "../middleware/authMiddleware.js";
const router = express.Router();
router.post("/register", upload.single("avatar"), register);
router.post("/login", login);
router.get("/me", protect, me);
export default router;
